// AUTO-GENERATED by scripts/generate-catalog.ts
// Do not edit manually. Run: node --experimental-strip-types scripts/generate-catalog.ts

export interface ComponentProp {
  name: string;
  type: string;
  required: boolean;
  default?: string;
  description: string;
}

export interface ComponentInfo {
  name: string;
  description: string;
  importName: string;
  props: ComponentProp[];
  variants?: string[];
  sizes?: string[];
  example: string;
  storybookPath: string;
}

export const components: ComponentInfo[] = [
  {
    "name": "Button",
    "description": "Clickable action button with multiple visual variants and sizes.",
    "importName": "Button",
    "props": [
      {
        "name": "variant",
        "type": "\"default\" | \"accent\" | \"destructive\" | \"outline\" | \"ghost\"",
        "required": false,
        "description": "Visual style of the button",
        "default": "\"default\""
      },
      {
        "name": "size",
        "type": "\"sm\" | \"default\" | \"lg\"",
        "required": false,
        "description": "Size of the button (height and padding)",
        "default": "\"default\""
      }
    ],
    "variants": [
      "default",
      "accent",
      "destructive",
      "outline",
      "ghost"
    ],
    "sizes": [
      "sm",
      "default",
      "lg"
    ],
    "example": "<Button variant=\"accent\" />",
    "storybookPath": "/docs/ui-button--docs"
  },
  {
    "name": "Chip",
    "description": "Toggle tag/pill with optional icon. Used for filters, feature toggles, tags.",
    "importName": "Chip",
    "props": [
      {
        "name": "icon",
        "type": "React.ReactNode",
        "required": false,
        "description": "Optional icon rendered before the label (pass a ReactNode)"
      },
      {
        "name": "selected",
        "type": "boolean",
        "required": false,
        "description": "Whether the chip is in the active/selected state"
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "Whether the chip is in the active/selected state"
      }
    ],
    "example": "<Chip>Label</Chip>",
    "storybookPath": "/docs/ui-chip--docs"
  },
  {
    "name": "ConfirmDialog",
    "description": "Confirmation card with title, description, and Cancel/Confirm action buttons.",
    "importName": "ConfirmDialog",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": true,
        "description": "Dialog heading text"
      },
      {
        "name": "description",
        "type": "React.ReactNode",
        "required": true,
        "description": "Explanatory text below the title. Accepts ReactNode for bold/styled text."
      },
      {
        "name": "confirmLabel",
        "type": "string",
        "required": false,
        "description": "Label for the confirm button",
        "default": "\"Confirm\""
      },
      {
        "name": "cancelLabel",
        "type": "string",
        "required": false,
        "description": "Label for the cancel button",
        "default": "\"Cancel\""
      },
      {
        "name": "variant",
        "type": "\"destructive\" | \"default\" | \"accent\"",
        "required": false,
        "description": "Visual style of the confirm button",
        "default": "\"outline\""
      },
      {
        "name": "onConfirm",
        "type": "() => void",
        "required": false,
        "description": "Called when the confirm button is clicked"
      },
      {
        "name": "onCancel",
        "type": "() => void",
        "required": false,
        "description": "Called when the cancel button is clicked"
      }
    ],
    "example": "<ConfirmDialog title=\"Example\" description={<>Content</>} />",
    "storybookPath": "/docs/ui-confirmdialog--docs"
  },
  {
    "name": "Toggle",
    "description": "On/off switch control. Supports controlled and uncontrolled modes.",
    "importName": "Toggle",
    "props": [
      {
        "name": "checked",
        "type": "boolean",
        "required": false,
        "description": "Controlled on/off state"
      },
      {
        "name": "defaultChecked",
        "type": "boolean",
        "required": false,
        "description": "Initial state for uncontrolled usage"
      },
      {
        "name": "onChange",
        "type": "(checked: boolean) => void",
        "required": false,
        "description": "Callback fired when toggle state changes. Receives the new boolean value."
      }
    ],
    "example": "<Toggle />",
    "storybookPath": "/docs/ui-toggle--docs"
  }
];
