// AUTO-GENERATED by scripts/generate-tokens.ts
// Do not edit manually. Run: node --experimental-strip-types scripts/generate-tokens.ts

export const designTokens = {
  colors: [
    {
        "name": "Navy",
        "hex": "#1E4C7E",
        "tailwind": "firm-navy",
        "usage": "Primary buttons, headings"
    },
    {
        "name": "Navy Light",
        "hex": "#2A6299",
        "tailwind": "firm-navy-light",
        "usage": "Hover state for primary"
    },
    {
        "name": "Navy Dark",
        "hex": "#153A61",
        "tailwind": "firm-navy-dark",
        "usage": "Active state, dark backgrounds"
    },
    {
        "name": "Lime",
        "hex": "#AED136",
        "tailwind": "firm-lime",
        "usage": "Accent buttons, focus rings, success"
    },
    {
        "name": "Lime Light",
        "hex": "#B5DD5A",
        "tailwind": "firm-lime-light",
        "usage": "Hover state for accent"
    },
    {
        "name": "Lime Dark",
        "hex": "#7FB01E",
        "tailwind": "firm-lime-dark",
        "usage": "Active state for accent"
    },
    {
        "name": "Destructive",
        "hex": "#FF6158",
        "tailwind": "firm-destructive",
        "usage": "Delete/danger actions"
    },
    {
        "name": "Destructive Dark",
        "hex": "#E5554D",
        "tailwind": "firm-destructive-dark",
        "usage": "Hover state for destructive"
    },
    {
        "name": "Foreground",
        "hex": "#4B5563",
        "tailwind": "firm-foreground",
        "usage": "Body text"
    },
    {
        "name": "Border",
        "hex": "#E5E7EB",
        "tailwind": "firm-border",
        "usage": "Card borders, dividers"
    },
    {
        "name": "Card",
        "hex": "#FFFFFF",
        "tailwind": "firm-card",
        "usage": "Card backgrounds"
    },
    {
        "name": "Background",
        "hex": "#F9FAFB",
        "tailwind": "firm-background",
        "usage": "Page background"
    },
    {
        "name": "Ring",
        "hex": "#AED136",
        "tailwind": "firm-ring",
        "usage": "Focus ring color"
    }
],
  typography: {
    sans: { font: "Inter", tailwind: "font-sans", usage: "Body text, buttons, labels (default)" },
    heading: { font: "Roboto", tailwind: "font-heading", usage: "Headings, titles, dialog headers" }
  },
  radius: [
    {
        "name": "Container",
        "value": "8px",
        "tailwind": "rounded-firm",
        "usage": "Cards, dialogs, containers"
    },
    {
        "name": "Element",
        "value": "4px",
        "tailwind": "rounded-firm-sm",
        "usage": "Buttons, inputs, small elements"
    }
],
  shadows: [
    {
        "name": "Firm Navy Shadow",
        "tailwind": "shadow-firm-navy",
        "usage": "Elevation for navy elements"
    },
    {
        "name": "Firm Lime Shadow",
        "tailwind": "shadow-firm-lime",
        "usage": "Elevation for lime elements"
    }
],
};
